interface=uap0
driver=nl80211
ssid=Ortho-Bender-FBAD
country_code=KR
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
rsn_pairwise=CCMP
wpa_passphrase=ortho-bender
ignore_broadcast_ssid=0
