# Layer configuration for meta-ortho-bender

BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "ortho-bender"
BBFILE_PATTERN_ortho-bender = "^${LAYERDIR}/"
BBFILE_PRIORITY_ortho-bender = "10"

LAYERDEPENDS_ortho-bender = "core meta-imx-bsp meta-ml qt6-layer"
LAYERSERIES_COMPAT_ortho-bender = "scarthgap"
