/**
 * @file motor_hal.h
 * @brief Unified motor driver HAL -- abstracts TMC260C, TMC5072, TMC5130, TMC5160
 * @author ortho-bender firmware team
 *
 * Provides a single motor control interface regardless of the underlying
 * Trinamic driver IC.  Each axis is bound at init time to one of four
 * driver backends via a function-pointer vtable (motor_hal_ops_t).
 *
 *   TMC260C-PA : STEP/DIR mode -- motion generated by step_gen.c (GPT timer)
 *   TMC5072    : SPI position mode, internal ramp generator (2-axis chip)
 *   TMC5130    : SPI position mode, internal ramp generator (single axis)
 *   TMC5160    : SPI position mode, internal ramp generator (single axis)
 *
 * Memory: ~32 bytes per motor_hal_t instance (static allocation).
 * No dynamic memory allocation.
 *
 * IEC 62304 SW Class: B
 */

#ifndef MOTOR_HAL_H
#define MOTOR_HAL_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ======================================================================
 * Driver Type Enumeration
 * ====================================================================== */

/** Supported Trinamic motor driver ICs */
typedef enum {
    MOTOR_DRV_TMC260C = 0,     /**< STEP/DIR + step_gen.c */
    MOTOR_DRV_TMC5072,          /**< SPI internal ramp (2-axis chip) */
    MOTOR_DRV_TMC5130,          /**< SPI internal ramp (single axis) */
    MOTOR_DRV_TMC5160,          /**< SPI internal ramp (single axis) */
    MOTOR_DRV_COUNT
} motor_driver_type_t;

/* ======================================================================
 * Result Codes
 * ====================================================================== */

/** Motor operation result */
typedef enum {
    MOTOR_OK = 0,               /**< Success */
    MOTOR_ERR_TIMEOUT,          /**< Operation timed out */
    MOTOR_ERR_STALL,            /**< StallGuard2 stall detected */
    MOTOR_ERR_OVERTEMP,         /**< Driver overtemperature shutdown */
    MOTOR_ERR_SHORT,            /**< Short to GND or VS detected */
    MOTOR_ERR_DRIVER_FAULT,     /**< Generic driver fault */
    MOTOR_ERR_INVALID_PARAM,    /**< Invalid parameter */
    MOTOR_ERR_NOT_INIT          /**< Driver not initialized */
} motor_result_t;

/* ======================================================================
 * Driver Status (unified across all TMC variants)
 * ====================================================================== */

/** Normalized driver status from any TMC variant */
typedef struct {
    uint8_t     ot;             /**< Overtemperature shutdown */
    uint8_t     otpw;           /**< Overtemperature pre-warning */
    uint8_t     s2ga;           /**< Short to GND phase A */
    uint8_t     s2gb;           /**< Short to GND phase B */
    uint8_t     ola;            /**< Open load phase A */
    uint8_t     olb;            /**< Open load phase B */
    uint8_t     stall;          /**< StallGuard2 stall detected */
    int16_t     sg_result;      /**< StallGuard2 load value (0-1023) */
} motor_status_t;

/* ======================================================================
 * Driver Operations (vtable)
 * ====================================================================== */

/**
 * @brief Function pointer table for driver-specific operations
 *
 * Each TMC driver backend provides an implementation of this structure.
 * The motor_hal_t dispatches all calls through these pointers.
 */
typedef struct motor_hal_ops {
    /** Initialize the driver hardware */
    motor_result_t (*init)(void *drv_ctx);

    /** Move to absolute position in microsteps */
    motor_result_t (*move_abs)(void *drv_ctx, int32_t target_steps,
                               uint32_t vmax, uint32_t amax);

    /** Check if target position has been reached */
    bool           (*position_reached)(void *drv_ctx);

    /** Get current position in microsteps */
    int32_t        (*get_position)(void *drv_ctx);

    /** Emergency stop -- immediate, no deceleration */
    void           (*emergency_stop)(void *drv_ctx);

    /** Poll driver status and fill normalized status struct */
    motor_result_t (*poll_status)(void *drv_ctx, motor_status_t *out);

    /** Enable motor outputs */
    void           (*enable)(void *drv_ctx);

    /** Disable motor outputs */
    void           (*disable)(void *drv_ctx);
} motor_hal_ops_t;

/* ======================================================================
 * Motor HAL Instance
 * ====================================================================== */

/** Per-axis motor HAL handle */
typedef struct {
    motor_driver_type_t     type;           /**< Driver IC type */
    void                   *drv_ctx;        /**< Pointer to driver instance (e.g. tmc5160_t) */
    const motor_hal_ops_t  *ops;            /**< Driver vtable */
    int32_t                 position_usteps; /**< Software position counter */
    uint8_t                 axis_id;        /**< Axis index (0-3) */
    bool                    initialized;    /**< HAL initialized flag */
} motor_hal_t;

/* ======================================================================
 * Public API
 * ====================================================================== */

/**
 * @brief Initialize motor HAL for a given axis
 * @param hal   Pointer to caller-allocated motor_hal_t (must have type, drv_ctx,
 *              ops, and axis_id pre-filled before calling)
 * @return MOTOR_OK on success, error code otherwise
 *
 * Calls the driver-specific init function and resets the software position
 * counter to zero.
 */
motor_result_t motor_hal_init(motor_hal_t *hal);

/**
 * @brief Move to absolute position in microsteps
 * @param hal    Motor HAL handle
 * @param steps  Target position (signed microsteps)
 * @param vmax   Maximum velocity (driver-specific units)
 * @param amax   Maximum acceleration (driver-specific units)
 * @return MOTOR_OK on success
 */
motor_result_t motor_hal_move_abs(motor_hal_t *hal, int32_t steps,
                                  uint32_t vmax, uint32_t amax);

/**
 * @brief Check if target position has been reached
 * @param hal  Motor HAL handle
 * @return true if position reached or no move in progress
 */
bool motor_hal_position_reached(motor_hal_t *hal);

/**
 * @brief Get current position in microsteps
 * @param hal  Motor HAL handle
 * @return Current position (signed)
 */
int32_t motor_hal_get_position(motor_hal_t *hal);

/**
 * @brief Emergency stop -- immediate halt, no deceleration ramp
 * @param hal  Motor HAL handle
 */
void motor_hal_emergency_stop(motor_hal_t *hal);

/**
 * @brief Poll driver status (overtemp, short, stall, etc.)
 * @param hal  Motor HAL handle
 * @param out  Output status struct (caller-allocated)
 * @return MOTOR_OK on success
 */
motor_result_t motor_hal_poll_status(motor_hal_t *hal, motor_status_t *out);

/**
 * @brief Enable motor outputs (de-assert DRV_ENN or equivalent)
 * @param hal  Motor HAL handle
 */
void motor_hal_enable(motor_hal_t *hal);

/**
 * @brief Disable motor outputs (assert DRV_ENN or equivalent)
 * @param hal  Motor HAL handle
 */
void motor_hal_disable(motor_hal_t *hal);

/* ======================================================================
 * Driver Ops Getters (implemented in each driver adapter)
 * ====================================================================== */

/**
 * @brief Get motor HAL ops for TMC260C-PA (STEP/DIR mode)
 * @return Pointer to static ops struct
 */
const motor_hal_ops_t *tmc260c_get_motor_hal_ops(void);

/**
 * @brief Get motor HAL ops for TMC5072 (SPI ramp, 2-axis)
 * @return Pointer to static ops struct
 */
const motor_hal_ops_t *tmc5072_get_motor_hal_ops(void);

/**
 * @brief Get motor HAL ops for TMC5130 (SPI ramp, single axis)
 * @return Pointer to static ops struct
 */
const motor_hal_ops_t *tmc5130_get_motor_hal_ops(void);

/**
 * @brief Get motor HAL ops for TMC5160 (SPI ramp, single axis)
 * @return Pointer to static ops struct
 */
const motor_hal_ops_t *tmc5160_get_motor_hal_ops(void);

#ifdef __cplusplus
}
#endif

#endif /* MOTOR_HAL_H */
